version: "2"
volumes:
  api_node_modules:
  app_node_modules:
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - SECRET=${SECRET}

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/foo/parkme.v1.yaml
    volumes: ["$PWD:/foo"]
    ports:
      - "8082:8080"

  app:
    build:
      context: ./frontend
      dockerfile: ../docker/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    depends_on:
      - api
