version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
