version: "2"
services:
  parkme-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
    environment:
      - SECRET=${SECRET}

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/foo/parkme.v1.yaml
    volumes: ["$PWD:/foo"]
    ports:
      - "8081:8080"
    links:
      - parkme-web

#  react-app:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    stdin_open: true
#    ports:
#      - "8082:8080"
#    volumes:
#      - ./frontend:/app
